/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class viewLogin extends javax.swing.JFrame {

    /**
     * Creates new form viewLogin
     */
    public viewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jb_vendedor = new javax.swing.JButton();
        jb_admin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_opciones = new javax.swing.JMenu();
        jmi_ayuda = new javax.swing.JMenuItem();
        jmi_olvido = new javax.swing.JMenuItem();
        jmi_cambio = new javax.swing.JMenuItem();
        jmi_cambio_validacion = new javax.swing.JMenuItem();
        jmi_cerrar = new javax.swing.JMenuItem();
        jmi_volver = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_vendedor.setText("Vendedor");

        jb_admin.setText("Admin");

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(null);

        jm_opciones.setBackground(new java.awt.Color(255, 102, 0));
        jm_opciones.setForeground(new java.awt.Color(255, 255, 255));
        jm_opciones.setText("Opciones");
        jm_opciones.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N

        jmi_ayuda.setBackground(new java.awt.Color(255, 102, 0));
        jmi_ayuda.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        jmi_ayuda.setText("Ayuda");
        jmi_ayuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_ayuda);

        jmi_olvido.setBackground(new java.awt.Color(255, 102, 0));
        jmi_olvido.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_olvido.setForeground(new java.awt.Color(255, 255, 255));
        jmi_olvido.setText("Olvide contraseña");
        jmi_olvido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_olvido);

        jmi_cambio.setBackground(new java.awt.Color(255, 102, 0));
        jmi_cambio.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_cambio.setForeground(new java.awt.Color(255, 255, 255));
        jmi_cambio.setText("Cambio contraseña");
        jmi_cambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_cambio);

        jmi_cambio_validacion.setBackground(new java.awt.Color(255, 102, 0));
        jmi_cambio_validacion.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_cambio_validacion.setForeground(new java.awt.Color(255, 255, 255));
        jmi_cambio_validacion.setText("Cambio validación");
        jmi_cambio_validacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_cambio_validacion);

        jmi_cerrar.setBackground(new java.awt.Color(255, 102, 0));
        jmi_cerrar.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jmi_cerrar.setText("Cerrar sesión");
        jmi_cerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_cerrar);

        jmi_volver.setBackground(new java.awt.Color(255, 102, 0));
        jmi_volver.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_volver.setForeground(new java.awt.Color(255, 255, 255));
        jmi_volver.setText("Volver");
        jmi_volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_volver);

        jMenuBar1.add(jm_opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addComponent(jb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JButton jb_admin;
    public javax.swing.JButton jb_vendedor;
    public javax.swing.JMenu jm_opciones;
    private javax.swing.JMenuItem jmi_ayuda;
    public javax.swing.JMenuItem jmi_cambio;
    public javax.swing.JMenuItem jmi_cambio_validacion;
    public javax.swing.JMenuItem jmi_cerrar;
    public javax.swing.JMenuItem jmi_olvido;
    public javax.swing.JMenuItem jmi_volver;
    // End of variables declaration//GEN-END:variables

    public void getContentPane(viewLogin viewLogin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
