/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class viewAdmin extends javax.swing.JPanel {

    /**
     * Creates new form viewAdmin
     */
    public viewAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_sucursales = new javax.swing.JButton();
        jb_catalogo = new javax.swing.JButton();
        jb_clientes = new javax.swing.JButton();
        jb_empleados = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1068, 543));
        setLayout(null);

        jb_sucursales.setText("Sucursales");
        add(jb_sucursales);
        jb_sucursales.setBounds(586, 73, 280, 126);

        jb_catalogo.setText("Catalogo");
        add(jb_catalogo);
        jb_catalogo.setBounds(586, 300, 280, 126);

        jb_clientes.setText("Clientes");
        add(jb_clientes);
        jb_clientes.setBounds(146, 300, 280, 126);

        jb_empleados.setText("Empleados");
        add(jb_empleados);
        jb_empleados.setBounds(146, 73, 280, 126);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_catalogo;
    private javax.swing.JButton jb_clientes;
    public javax.swing.JButton jb_empleados;
    private javax.swing.JButton jb_sucursales;
    // End of variables declaration//GEN-END:variables
}
