/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author manl_
 */
public class viewVentasConsulta extends javax.swing.JPanel {

    /**
     * Creates new form viewVentasConsulta
     */
    public viewVentasConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_consulta = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ventas = new javax.swing.JTable();
        jl_idsucursal = new javax.swing.JLabel();
        jcb_idsucursal = new javax.swing.JComboBox<>();
        jl_producto_diain = new javax.swing.JLabel();
        jtf_producto_diain = new javax.swing.JTextField();
        jl_empleado_diafin = new javax.swing.JLabel();
        jtf_empleado_diafin = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jt_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Sucursal", "Empleado", "Id Venta", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_ventas);

        add(jScrollPane2);
        jScrollPane2.setBounds(71, 122, 969, 363);

        jl_idsucursal.setText("Id Sucursal:");
        add(jl_idsucursal);
        jl_idsucursal.setBounds(71, 61, 57, 15);

        jcb_idsucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        add(jcb_idsucursal);
        jcb_idsucursal.setBounds(140, 56, 40, 24);

        jl_producto_diain.setText("Buscar producto/dia: ");
        add(jl_producto_diain);
        jl_producto_diain.setBounds(301, 61, 104, 15);
        add(jtf_producto_diain);
        jtf_producto_diain.setBounds(423, 59, 257, 19);

        jl_empleado_diafin.setText("Buscar empleado/dia_final:");
        add(jl_empleado_diafin);
        jl_empleado_diafin.setBounds(275, 88, 130, 15);
        add(jtf_empleado_diafin);
        jtf_empleado_diafin.setBounds(423, 86, 257, 19);

        jRadioButton1.setBackground(new java.awt.Color(252, 252, 252));
        bg_consulta.add(jRadioButton1);
        jRadioButton1.setText("Día");
        add(jRadioButton1);
        jRadioButton1.setBounds(314, 17, 40, 23);

        jRadioButton2.setBackground(new java.awt.Color(252, 252, 252));
        bg_consulta.add(jRadioButton2);
        jRadioButton2.setText("Rango de días");
        add(jRadioButton2);
        jRadioButton2.setBounds(378, 17, 94, 23);

        jRadioButton3.setBackground(new java.awt.Color(252, 252, 252));
        bg_consulta.add(jRadioButton3);
        jRadioButton3.setText("Sucursal");
        add(jRadioButton3);
        jRadioButton3.setBounds(490, 17, 68, 23);

        jRadioButton4.setBackground(new java.awt.Color(252, 252, 252));
        bg_consulta.add(jRadioButton4);
        jRadioButton4.setText("Empleado");
        add(jRadioButton4);
        jRadioButton4.setBounds(576, 17, 71, 23);

        jRadioButton5.setBackground(new java.awt.Color(252, 252, 252));
        bg_consulta.add(jRadioButton5);
        jRadioButton5.setText("Producto");
        add(jRadioButton5);
        jRadioButton5.setBounds(665, 17, 68, 23);

        jLabel1.setText("Consulta por:");
        add(jLabel1);
        jLabel1.setBounds(116, 21, 64, 15);

        jRadioButton6.setBackground(new java.awt.Color(252, 252, 252));
        bg_consulta.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("General");
        add(jRadioButton6);
        jRadioButton6.setBounds(233, 17, 63, 23);

        jButton1.setText("Buscar");
        add(jButton1);
        jButton1.setBounds(713, 79, 69, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1100, 540);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_consulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton4;
    public javax.swing.JRadioButton jRadioButton5;
    public javax.swing.JRadioButton jRadioButton6;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> jcb_idsucursal;
    public javax.swing.JLabel jl_empleado_diafin;
    public javax.swing.JLabel jl_idsucursal;
    public javax.swing.JLabel jl_producto_diain;
    private javax.swing.JTable jt_ventas;
    public javax.swing.JTextField jtf_empleado_diafin;
    public javax.swing.JTextField jtf_producto_diain;
    // End of variables declaration//GEN-END:variables
}
