/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author manl_
 */
public class viewVentasConsulta extends javax.swing.JPanel {

    /**
     * Creates new form viewVentasConsulta
     */
    public viewVentasConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_consulta = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ventas = new javax.swing.JTable();
        jl_idsucursal = new javax.swing.JLabel();
        jcb_idsucursal = new javax.swing.JComboBox<>();
        jl_producto_diain = new javax.swing.JLabel();
        jtf_producto_diain = new javax.swing.JTextField();
        jl_empleado_diafin = new javax.swing.JLabel();
        jtf_empleado_diafin = new javax.swing.JTextField();
        jrb_dia = new javax.swing.JRadioButton();
        jrb_rangos = new javax.swing.JRadioButton();
        jrb_sucursal = new javax.swing.JRadioButton();
        jrb_empleado = new javax.swing.JRadioButton();
        jrb_producto = new javax.swing.JRadioButton();
        jrb_general = new javax.swing.JRadioButton();
        jl_consulta = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        jl_titulo = new javax.swing.JLabel();
        jl_fondo = new javax.swing.JLabel();

        setLayout(null);

        jt_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Sucursal", "Empleado", "Id Venta", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_ventas);

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 170, 969, 340);

        jl_idsucursal.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_idsucursal.setForeground(new java.awt.Color(255, 102, 0));
        jl_idsucursal.setText("Id Sucursal:");
        add(jl_idsucursal);
        jl_idsucursal.setBounds(80, 100, 82, 17);

        jcb_idsucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        add(jcb_idsucursal);
        jcb_idsucursal.setBounds(170, 100, 40, 24);

        jl_producto_diain.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_producto_diain.setForeground(new java.awt.Color(255, 102, 0));
        jl_producto_diain.setText("Buscar producto/dia: ");
        add(jl_producto_diain);
        jl_producto_diain.setBounds(290, 100, 153, 17);
        add(jtf_producto_diain);
        jtf_producto_diain.setBounds(440, 100, 257, 19);

        jl_empleado_diafin.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_empleado_diafin.setForeground(new java.awt.Color(255, 102, 0));
        jl_empleado_diafin.setText("Buscar empleado/dia_final:");
        add(jl_empleado_diafin);
        jl_empleado_diafin.setBounds(250, 130, 186, 17);
        add(jtf_empleado_diafin);
        jtf_empleado_diafin.setBounds(440, 130, 257, 19);

        jrb_dia.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        bg_consulta.add(jrb_dia);
        jrb_dia.setText("Día");
        add(jrb_dia);
        jrb_dia.setBounds(330, 60, 40, 23);

        jrb_rangos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        bg_consulta.add(jrb_rangos);
        jrb_rangos.setText("Rango de días");
        add(jrb_rangos);
        jrb_rangos.setBounds(400, 60, 94, 23);

        jrb_sucursal.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        bg_consulta.add(jrb_sucursal);
        jrb_sucursal.setText("Sucursal");
        add(jrb_sucursal);
        jrb_sucursal.setBounds(510, 60, 68, 23);

        jrb_empleado.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        bg_consulta.add(jrb_empleado);
        jrb_empleado.setText("Empleado");
        add(jrb_empleado);
        jrb_empleado.setBounds(600, 60, 71, 23);

        jrb_producto.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        bg_consulta.add(jrb_producto);
        jrb_producto.setText("Producto");
        add(jrb_producto);
        jrb_producto.setBounds(690, 60, 68, 23);

        jrb_general.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        bg_consulta.add(jrb_general);
        jrb_general.setSelected(true);
        jrb_general.setText("General");
        add(jrb_general);
        jrb_general.setBounds(250, 60, 63, 23);

        jl_consulta.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_consulta.setForeground(new java.awt.Color(255, 102, 0));
        jl_consulta.setText("Consulta por:");
        add(jl_consulta);
        jl_consulta.setBounds(130, 60, 110, 17);

        jb_buscar.setBackground(new java.awt.Color(255, 102, 0));
        jb_buscar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_buscar.setText("Buscar");
        jb_buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jb_buscar);
        jb_buscar.setBounds(730, 110, 90, 23);

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 46)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setText("Consulta de ventas");
        add(jl_titulo);
        jl_titulo.setBounds(260, 10, 430, 52);

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        add(jl_fondo);
        jl_fondo.setBounds(0, 0, 1100, 570);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_consulta;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_buscar;
    public javax.swing.JComboBox<String> jcb_idsucursal;
    private javax.swing.JLabel jl_consulta;
    public javax.swing.JLabel jl_empleado_diafin;
    private javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_idsucursal;
    public javax.swing.JLabel jl_producto_diain;
    private javax.swing.JLabel jl_titulo;
    public javax.swing.JRadioButton jrb_dia;
    public javax.swing.JRadioButton jrb_empleado;
    public javax.swing.JRadioButton jrb_general;
    public javax.swing.JRadioButton jrb_producto;
    public javax.swing.JRadioButton jrb_rangos;
    public javax.swing.JRadioButton jrb_sucursal;
    private javax.swing.JTable jt_ventas;
    public javax.swing.JTextField jtf_empleado_diafin;
    public javax.swing.JTextField jtf_producto_diain;
    // End of variables declaration//GEN-END:variables
}
