/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Abi Montes
 */
public class viewSucursal extends javax.swing.JPanel {

    /**
     * Creates new form viewSucursal
     */
    public viewSucursal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_sucursales = new javax.swing.JTable();
        jl_id = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jl_colonia = new javax.swing.JLabel();
        jtf_colonia = new javax.swing.JTextField();
        jl_nointerior = new javax.swing.JLabel();
        jtf_nointerior = new javax.swing.JTextField();
        jl_telefono = new javax.swing.JLabel();
        jtf_telefono = new javax.swing.JTextField();
        jl_calle = new javax.swing.JLabel();
        jtf_calle = new javax.swing.JTextField();
        jl_noexterior = new javax.swing.JLabel();
        jtf_noexterior = new javax.swing.JTextField();
        jl_cp = new javax.swing.JLabel();
        jtf_cp = new javax.swing.JTextField();
        jl_datospersonales = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jb_agregar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jl_nointerior1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 68)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Sucursales");
        add(jl_titulo);
        jl_titulo.setBounds(150, 10, 754, 77);
        add(jtf_buscar);
        jtf_buscar.setBounds(230, 90, 661, 19);

        jt_sucursales = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColumnIndex){
                return false;
            }};
            jt_sucursales.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
            jt_sucursales.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String [] {
                    "Id", "Calle", "Colonia", "No ext", "No int", "Cp", "Telefono"
                }
            ));
            jScrollPane1.setViewportView(jt_sucursales);

            add(jScrollPane1);
            jScrollPane1.setBounds(20, 130, 1050, 92);

            jl_id.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_id.setForeground(new java.awt.Color(255, 102, 0));
            jl_id.setText("Id");
            add(jl_id);
            jl_id.setBounds(100, 300, 42, 21);

            jtf_id.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_id.setForeground(new java.awt.Color(255, 102, 0));
            jtf_id.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jtf_idActionPerformed(evt);
                }
            });
            add(jtf_id);
            jtf_id.setBounds(140, 300, 115, 25);

            jl_colonia.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_colonia.setForeground(new java.awt.Color(255, 102, 0));
            jl_colonia.setText("Colonia");
            add(jl_colonia);
            jl_colonia.setBounds(630, 290, 72, 21);

            jtf_colonia.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_colonia.setForeground(new java.awt.Color(255, 102, 0));
            add(jtf_colonia);
            jtf_colonia.setBounds(720, 290, 213, 25);

            jl_nointerior.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_nointerior.setForeground(new java.awt.Color(255, 102, 0));
            jl_nointerior.setText("No interior");
            add(jl_nointerior);
            jl_nointerior.setBounds(20, 360, 109, 21);

            jtf_nointerior.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_nointerior.setForeground(new java.awt.Color(255, 102, 0));
            add(jtf_nointerior);
            jtf_nointerior.setBounds(130, 360, 140, 25);

            jl_telefono.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_telefono.setForeground(new java.awt.Color(255, 102, 0));
            jl_telefono.setText("Telefono");
            add(jl_telefono);
            jl_telefono.setBounds(20, 420, 73, 21);

            jtf_telefono.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_telefono.setForeground(new java.awt.Color(255, 102, 0));
            add(jtf_telefono);
            jtf_telefono.setBounds(130, 420, 162, 25);

            jl_calle.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_calle.setForeground(new java.awt.Color(255, 102, 0));
            jl_calle.setText("Calle");
            add(jl_calle);
            jl_calle.setBounds(340, 290, 54, 21);

            jtf_calle.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_calle.setForeground(new java.awt.Color(255, 102, 0));
            add(jtf_calle);
            jtf_calle.setBounds(410, 290, 147, 25);

            jl_noexterior.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_noexterior.setForeground(new java.awt.Color(255, 102, 0));
            jl_noexterior.setText("No exterior");
            add(jl_noexterior);
            jl_noexterior.setBounds(310, 360, 100, 21);

            jtf_noexterior.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_noexterior.setForeground(new java.awt.Color(255, 102, 0));
            add(jtf_noexterior);
            jtf_noexterior.setBounds(430, 360, 131, 25);

            jl_cp.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_cp.setForeground(new java.awt.Color(255, 102, 0));
            jl_cp.setText("Cp");
            add(jl_cp);
            jl_cp.setBounds(660, 360, 42, 21);

            jtf_cp.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jtf_cp.setForeground(new java.awt.Color(255, 102, 0));
            add(jtf_cp);
            jtf_cp.setBounds(730, 360, 156, 25);

            jl_datospersonales.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_datospersonales.setForeground(new java.awt.Color(255, 102, 0));
            jl_datospersonales.setText("Datos Sucursal");
            add(jl_datospersonales);
            jl_datospersonales.setBounds(20, 240, 172, 21);

            jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
            add(jSeparator1);
            jSeparator1.setBounds(20, 270, 1040, 10);

            jb_agregar.setBackground(new java.awt.Color(255, 102, 0));
            jb_agregar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
            jb_agregar.setForeground(new java.awt.Color(255, 255, 255));
            jb_agregar.setText("Nuevo");
            jb_agregar.setBorder(null);
            add(jb_agregar);
            jb_agregar.setBounds(20, 480, 130, 40);

            jb_modificar.setBackground(new java.awt.Color(255, 102, 0));
            jb_modificar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
            jb_modificar.setForeground(new java.awt.Color(255, 255, 255));
            jb_modificar.setText("Modificar");
            jb_modificar.setBorder(null);
            add(jb_modificar);
            jb_modificar.setBounds(190, 480, 130, 40);

            jb_guardar.setBackground(new java.awt.Color(255, 102, 0));
            jb_guardar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
            jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
            jb_guardar.setText("Guardar");
            jb_guardar.setBorder(null);
            jb_guardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jb_guardarActionPerformed(evt);
                }
            });
            add(jb_guardar);
            jb_guardar.setBounds(630, 480, 130, 40);

            jb_eliminar.setBackground(new java.awt.Color(255, 102, 0));
            jb_eliminar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
            jb_eliminar.setForeground(new java.awt.Color(255, 255, 255));
            jb_eliminar.setText("Eliminar");
            jb_eliminar.setBorder(null);
            add(jb_eliminar);
            jb_eliminar.setBounds(350, 480, 130, 40);

            jb_cancelar.setBackground(new java.awt.Color(255, 102, 0));
            jb_cancelar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
            jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
            jb_cancelar.setText("Cancelar");
            jb_cancelar.setBorder(null);
            add(jb_cancelar);
            jb_cancelar.setBounds(800, 480, 130, 40);

            jSeparator2.setForeground(new java.awt.Color(255, 102, 0));
            add(jSeparator2);
            jSeparator2.setBounds(20, 460, 1040, 10);

            jl_nointerior1.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
            jl_nointerior1.setForeground(new java.awt.Color(255, 102, 0));
            jl_nointerior1.setText("Buscar:");
            add(jl_nointerior1);
            jl_nointerior1.setBounds(160, 90, 109, 21);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
            add(jLabel1);
            jLabel1.setBounds(0, -10, 1100, 590);
        }// </editor-fold>//GEN-END:initComponents

    private void jtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton jb_agregar;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_modificar;
    private javax.swing.JLabel jl_calle;
    private javax.swing.JLabel jl_colonia;
    private javax.swing.JLabel jl_cp;
    private javax.swing.JLabel jl_datospersonales;
    private javax.swing.JLabel jl_id;
    private javax.swing.JLabel jl_noexterior;
    private javax.swing.JLabel jl_nointerior;
    private javax.swing.JLabel jl_nointerior1;
    private javax.swing.JLabel jl_telefono;
    private javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_sucursales;
    private javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_calle;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_cp;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_noexterior;
    public javax.swing.JTextField jtf_nointerior;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
