/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author manl_
 */
public class viewDetallecompra extends javax.swing.JPanel {

    /**
     * Creates new form viewDetallecompra
     */
    public viewDetallecompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_detallecompra = new javax.swing.JTable();
        jb_ingresar_detalle = new javax.swing.JButton();
        jb_modificar_detalle = new javax.swing.JButton();
        jb_guardar_detalle = new javax.swing.JButton();
        jb_cancelar_detalle = new javax.swing.JButton();
        jb_eliminar_detalle = new javax.swing.JButton();
        jl_numero_factura = new javax.swing.JLabel();
        jl_nombre_factura = new javax.swing.JLabel();
        jl_id_producto = new javax.swing.JLabel();
        jtf_id_producto = new javax.swing.JTextField();
        jl_cantidad = new javax.swing.JLabel();
        jtf_cantidad = new javax.swing.JTextField();
        jl_subtotal = new javax.swing.JLabel();
        jtd_subtotal = new javax.swing.JTextField();
        jl_total = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jb_finalizar = new javax.swing.JButton();
        jl_titulo = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jl_fondo = new javax.swing.JLabel();

        setLayout(null);

        jt_detallecompra = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColumnIndex){
                return false;
            }
        };
        jt_detallecompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id detalle", "Factura", "Id producto", "Cantidad", "Subtotal", "Total"
            }
        ));
        jScrollPane1.setViewportView(jt_detallecompra);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 80, 740, 220);

        jb_ingresar_detalle.setBackground(new java.awt.Color(255, 102, 0));
        jb_ingresar_detalle.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_ingresar_detalle.setText("Ingresar detalle");
        jb_ingresar_detalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jb_ingresar_detalle);
        jb_ingresar_detalle.setBounds(810, 80, 130, 30);

        jb_modificar_detalle.setBackground(new java.awt.Color(255, 102, 0));
        jb_modificar_detalle.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_modificar_detalle.setText("Modificar detalle");
        jb_modificar_detalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jb_modificar_detalle);
        jb_modificar_detalle.setBounds(810, 110, 130, 30);

        jb_guardar_detalle.setBackground(new java.awt.Color(255, 102, 0));
        jb_guardar_detalle.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_guardar_detalle.setText("Guardar detalle");
        jb_guardar_detalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jb_guardar_detalle);
        jb_guardar_detalle.setBounds(810, 203, 130, 30);

        jb_cancelar_detalle.setBackground(new java.awt.Color(255, 102, 0));
        jb_cancelar_detalle.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_cancelar_detalle.setText("Cancelar detalle");
        jb_cancelar_detalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_cancelar_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelar_detalleActionPerformed(evt);
            }
        });
        add(jb_cancelar_detalle);
        jb_cancelar_detalle.setBounds(810, 230, 130, 30);

        jb_eliminar_detalle.setBackground(new java.awt.Color(255, 102, 0));
        jb_eliminar_detalle.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_eliminar_detalle.setText("Eliminar detalle");
        jb_eliminar_detalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jb_eliminar_detalle);
        jb_eliminar_detalle.setBounds(810, 140, 130, 30);

        jl_numero_factura.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_numero_factura.setForeground(new java.awt.Color(255, 102, 0));
        jl_numero_factura.setText("Numero de factura:");
        add(jl_numero_factura);
        jl_numero_factura.setBounds(60, 340, 136, 17);

        jl_nombre_factura.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_nombre_factura.setForeground(new java.awt.Color(255, 255, 255));
        jl_nombre_factura.setText(" ");
        add(jl_nombre_factura);
        jl_nombre_factura.setBounds(210, 340, 180, 17);

        jl_id_producto.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_id_producto.setForeground(new java.awt.Color(255, 102, 0));
        jl_id_producto.setText("id producto:");
        add(jl_id_producto);
        jl_id_producto.setBounds(93, 372, 84, 17);
        add(jtf_id_producto);
        jtf_id_producto.setBounds(190, 370, 50, 19);

        jl_cantidad.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_cantidad.setForeground(new java.awt.Color(255, 102, 0));
        jl_cantidad.setText("Cantidad:");
        add(jl_cantidad);
        jl_cantidad.setBounds(105, 405, 62, 17);
        add(jtf_cantidad);
        jtf_cantidad.setBounds(190, 400, 50, 19);

        jl_subtotal.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_subtotal.setForeground(new java.awt.Color(255, 102, 0));
        jl_subtotal.setText("Subtotal:");
        add(jl_subtotal);
        jl_subtotal.setBounds(269, 374, 60, 17);
        add(jtd_subtotal);
        jtd_subtotal.setBounds(340, 370, 63, 19);

        jl_total.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_total.setForeground(new java.awt.Color(255, 102, 0));
        jl_total.setText("Total:");
        add(jl_total);
        jl_total.setBounds(285, 405, 38, 17);
        add(jtf_total);
        jtf_total.setBounds(340, 400, 63, 19);

        jt_productos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColumnIndex){
                return false;
            }
        };
        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id producto", "Nombre producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_productos);

        add(jScrollPane2);
        jScrollPane2.setBounds(560, 350, 269, 133);

        jb_finalizar.setBackground(new java.awt.Color(255, 102, 0));
        jb_finalizar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_finalizar.setText("Finalizar");
        jb_finalizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jb_finalizar);
        jb_finalizar.setBounds(860, 430, 80, 40);

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 46)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setText("Detalle de compra");
        add(jl_titulo);
        jl_titulo.setBounds(290, 10, 410, 60);
        add(jtf_buscar);
        jtf_buscar.setBounds(623, 326, 200, 19);

        jl_buscar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_buscar.setForeground(new java.awt.Color(255, 102, 0));
        jl_buscar.setText("Producto:");
        add(jl_buscar);
        jl_buscar.setBounds(550, 330, 70, 17);

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        add(jl_fondo);
        jl_fondo.setBounds(0, 0, 1060, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelar_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelar_detalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelar_detalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jb_cancelar_detalle;
    public javax.swing.JButton jb_eliminar_detalle;
    public javax.swing.JButton jb_finalizar;
    public javax.swing.JButton jb_guardar_detalle;
    public javax.swing.JButton jb_ingresar_detalle;
    public javax.swing.JButton jb_modificar_detalle;
    private javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_cantidad;
    private javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_id_producto;
    public javax.swing.JLabel jl_nombre_factura;
    public javax.swing.JLabel jl_numero_factura;
    public javax.swing.JLabel jl_subtotal;
    private javax.swing.JLabel jl_titulo;
    public javax.swing.JLabel jl_total;
    public javax.swing.JTable jt_detallecompra;
    public javax.swing.JTable jt_productos;
    public javax.swing.JTextField jtd_subtotal;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_cantidad;
    public javax.swing.JTextField jtf_id_producto;
    public javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
