/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Abi Montes
 */
public class viewProveedor extends javax.swing.JPanel {

    /**
     * Creates new form viewProveedor
     */
    public viewProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jl_datospersonales = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jl_rfc = new javax.swing.JLabel();
        jtf_rfc = new javax.swing.JTextField();
        jtf_correo = new javax.swing.JTextField();
        jl_correo = new javax.swing.JLabel();
        jtf_calle = new javax.swing.JTextField();
        jl_calle = new javax.swing.JLabel();
        jtf_colonia = new javax.swing.JTextField();
        jl_colonia = new javax.swing.JLabel();
        jtf_no_ext = new javax.swing.JTextField();
        jl_no_ext = new javax.swing.JLabel();
        jtf_cp = new javax.swing.JTextField();
        jl_cp = new javax.swing.JLabel();
        jl_datos = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jl_razons = new javax.swing.JLabel();
        jtf_razons = new javax.swing.JTextField();
        jl_telefono = new javax.swing.JLabel();
        jtf_telefono = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 68)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Proveedores");
        add(jl_titulo);
        jl_titulo.setBounds(250, 10, 672, 77);
        add(jtf_buscar);
        jtf_buscar.setBounds(90, 90, 590, 19);

        jb_buscar.setBackground(new java.awt.Color(255, 102, 0));
        jb_buscar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jb_buscar.setText("Buscar");
        jb_buscar.setBorder(null);
        add(jb_buscar);
        jb_buscar.setBounds(690, 90, 72, 17);

        jTable1.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RFC", "Razons", "Calle", "Colonia", "No ext", "Cp", "Telefono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 130, 930, 120);

        jl_datospersonales.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_datospersonales.setForeground(new java.awt.Color(255, 102, 0));
        jl_datospersonales.setText("Datos Personales");
        add(jl_datospersonales);
        jl_datospersonales.setBounds(10, 260, 172, 21);

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        add(jSeparator1);
        jSeparator1.setBounds(10, 290, 1020, 10);

        jl_rfc.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_rfc.setForeground(new java.awt.Color(255, 102, 0));
        jl_rfc.setText("RFC:");
        add(jl_rfc);
        jl_rfc.setBounds(90, 310, 40, 20);

        jtf_rfc.setEditable(false);
        add(jtf_rfc);
        jtf_rfc.setBounds(80, 330, 160, 19);

        jtf_correo.setEditable(false);
        add(jtf_correo);
        jtf_correo.setBounds(540, 330, 148, 19);

        jl_correo.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_correo.setForeground(new java.awt.Color(255, 102, 0));
        jl_correo.setText("Correo:");
        add(jl_correo);
        jl_correo.setBounds(530, 300, 50, 17);

        jtf_calle.setEditable(false);
        add(jtf_calle);
        jtf_calle.setBounds(60, 430, 165, 19);

        jl_calle.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_calle.setForeground(new java.awt.Color(255, 102, 0));
        jl_calle.setText("Calle:");
        add(jl_calle);
        jl_calle.setBounds(60, 400, 40, 17);

        jtf_colonia.setEditable(false);
        add(jtf_colonia);
        jtf_colonia.setBounds(280, 430, 165, 19);

        jl_colonia.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_colonia.setForeground(new java.awt.Color(255, 102, 0));
        jl_colonia.setText("Colonia:");
        add(jl_colonia);
        jl_colonia.setBounds(280, 400, 60, 17);

        jtf_no_ext.setEditable(false);
        add(jtf_no_ext);
        jtf_no_ext.setBounds(540, 430, 90, 19);

        jl_no_ext.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_no_ext.setForeground(new java.awt.Color(255, 102, 0));
        jl_no_ext.setText("No_exterior:");
        add(jl_no_ext);
        jl_no_ext.setBounds(540, 400, 90, 20);

        jtf_cp.setEditable(false);
        add(jtf_cp);
        jtf_cp.setBounds(760, 430, 80, 19);

        jl_cp.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_cp.setForeground(new java.awt.Color(255, 102, 0));
        jl_cp.setText("C.P:");
        add(jl_cp);
        jl_cp.setBounds(760, 400, 70, 20);

        jl_datos.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_datos.setForeground(new java.awt.Color(255, 102, 0));
        jl_datos.setText("Dirección");
        add(jl_datos);
        jl_datos.setBounds(10, 360, 160, 21);
        add(jSeparator2);
        jSeparator2.setBounds(10, 382, 1020, 10);

        jl_razons.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_razons.setForeground(new java.awt.Color(255, 102, 0));
        jl_razons.setText("Razón Social");
        add(jl_razons);
        jl_razons.setBounds(290, 310, 86, 17);

        jtf_razons.setEditable(false);
        add(jtf_razons);
        jtf_razons.setBounds(290, 330, 160, 19);

        jl_telefono.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_telefono.setForeground(new java.awt.Color(255, 102, 0));
        jl_telefono.setText("Teléfono:");
        add(jl_telefono);
        jl_telefono.setBounds(760, 300, 70, 20);

        jtf_telefono.setEditable(false);
        add(jtf_telefono);
        jtf_telefono.setBounds(760, 330, 150, 19);

        jb_agregar.setBackground(new java.awt.Color(255, 102, 0));
        jb_agregar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jb_agregar.setText("Nuevo");
        jb_agregar.setBorder(null);
        add(jb_agregar);
        jb_agregar.setBounds(30, 490, 110, 40);

        jb_modificar.setBackground(new java.awt.Color(255, 102, 0));
        jb_modificar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificar.setText("Modificar");
        jb_modificar.setBorder(null);
        add(jb_modificar);
        jb_modificar.setBounds(160, 490, 110, 40);

        jb_guardar.setBackground(new java.awt.Color(255, 102, 0));
        jb_guardar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");
        jb_guardar.setBorder(null);
        add(jb_guardar);
        jb_guardar.setBounds(630, 490, 110, 40);

        jb_eliminar.setBackground(new java.awt.Color(255, 102, 0));
        jb_eliminar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jb_eliminar.setText("Eliminar");
        jb_eliminar.setBorder(null);
        add(jb_eliminar);
        jb_eliminar.setBounds(290, 490, 110, 40);

        jb_cancelar.setBackground(new java.awt.Color(255, 102, 0));
        jb_cancelar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setBorder(null);
        add(jb_cancelar);
        jb_cancelar.setBounds(750, 490, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 560);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable jTable1;
    public javax.swing.JButton jb_agregar;
    public javax.swing.JButton jb_buscar;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_modificar;
    private javax.swing.JLabel jl_calle;
    private javax.swing.JLabel jl_colonia;
    private javax.swing.JLabel jl_correo;
    private javax.swing.JLabel jl_cp;
    private javax.swing.JLabel jl_datos;
    private javax.swing.JLabel jl_datospersonales;
    private javax.swing.JLabel jl_no_ext;
    private javax.swing.JLabel jl_razons;
    private javax.swing.JLabel jl_rfc;
    private javax.swing.JLabel jl_telefono;
    private javax.swing.JLabel jl_titulo;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_calle;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_correo;
    public javax.swing.JTextField jtf_cp;
    public javax.swing.JTextField jtf_no_ext;
    public javax.swing.JTextField jtf_razons;
    public javax.swing.JTextField jtf_rfc;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
