/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class viewInicio extends javax.swing.JPanel {

    /**
     * Creates new form viewInicio
     */
    public viewInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_icono = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jl_password = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jb_entrar = new javax.swing.JButton();
        jpf_password = new javax.swing.JPasswordField();
        jl_fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1055, 575));
        setLayout(null);

        jl_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuetzalStockNARANJA.png"))); // NOI18N
        jl_icono.setMaximumSize(new java.awt.Dimension(200, 250));
        add(jl_icono);
        jl_icono.setBounds(426, 99, 286, 223);

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 68)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setText("Bienvenido");
        add(jl_titulo);
        jl_titulo.setBounds(360, 16, 352, 77);

        jl_usuario.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_usuario.setForeground(new java.awt.Color(255, 102, 0));
        jl_usuario.setText("Usuario: ");
        add(jl_usuario);
        jl_usuario.setBounds(388, 333, 78, 21);

        jl_password.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_password.setForeground(new java.awt.Color(255, 102, 0));
        jl_password.setText("Contraseña: ");
        add(jl_password);
        jl_password.setBounds(388, 386, 110, 21);
        add(jtf_usuario);
        jtf_usuario.setBounds(388, 360, 232, 20);

        jb_entrar.setBackground(new java.awt.Color(255, 102, 0));
        jb_entrar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_entrar.setText("Entrar");
        jb_entrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jb_entrar);
        jb_entrar.setBounds(450, 451, 151, 33);
        add(jpf_password);
        jpf_password.setBounds(390, 420, 230, 20);

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        add(jl_fondo);
        jl_fondo.setBounds(0, 0, 1090, 600);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_entrar;
    public javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_icono;
    public javax.swing.JLabel jl_password;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JLabel jl_usuario;
    public javax.swing.JPasswordField jpf_password;
    public javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
