/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class viewLogin extends javax.swing.JFrame {

    /**
     * Creates new form viewLogin
     */
    public viewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jl_icono = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jl_password = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jtf_password = new javax.swing.JTextField();
        jb_entrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_opciones = new javax.swing.JMenu();
        jmi_ayuda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_olvido = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmi_cambio = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmi_cambio_validacion = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmi_cerrar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmi_volver = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jl_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuetzalStockNARANJA.png"))); // NOI18N
        jl_icono.setMaximumSize(new java.awt.Dimension(200, 250));

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 68)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setText("Bienvenido");

        jl_usuario.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_usuario.setForeground(new java.awt.Color(255, 102, 0));
        jl_usuario.setText("Usuario: ");

        jl_password.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_password.setForeground(new java.awt.Color(255, 102, 0));
        jl_password.setText("Contraseña: ");

        jb_entrar.setBackground(new java.awt.Color(255, 102, 0));
        jb_entrar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_entrar.setText("Entrar");
        jb_entrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jl_usuario)
                                        .addComponent(jl_password)
                                        .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jb_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(null);

        jm_opciones.setBackground(new java.awt.Color(255, 102, 0));
        jm_opciones.setForeground(new java.awt.Color(255, 255, 255));
        jm_opciones.setText("Opciones");
        jm_opciones.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N

        jmi_ayuda.setBackground(new java.awt.Color(255, 102, 0));
        jmi_ayuda.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        jmi_ayuda.setText("Ayuda");
        jmi_ayuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_ayuda);
        jm_opciones.add(jSeparator1);

        jmi_olvido.setBackground(new java.awt.Color(255, 102, 0));
        jmi_olvido.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_olvido.setForeground(new java.awt.Color(255, 255, 255));
        jmi_olvido.setText("Olvide contraseña");
        jmi_olvido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_olvido);
        jm_opciones.add(jSeparator2);

        jmi_cambio.setBackground(new java.awt.Color(255, 102, 0));
        jmi_cambio.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_cambio.setForeground(new java.awt.Color(255, 255, 255));
        jmi_cambio.setText("Cambio contraseña");
        jmi_cambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_cambio);
        jm_opciones.add(jSeparator3);

        jmi_cambio_validacion.setBackground(new java.awt.Color(255, 102, 0));
        jmi_cambio_validacion.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_cambio_validacion.setForeground(new java.awt.Color(255, 255, 255));
        jmi_cambio_validacion.setText("Cambio validación");
        jmi_cambio_validacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_cambio_validacion);
        jm_opciones.add(jSeparator4);

        jmi_cerrar.setBackground(new java.awt.Color(255, 102, 0));
        jmi_cerrar.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jmi_cerrar.setText("Cerrar sesión");
        jmi_cerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_cerrar);
        jm_opciones.add(jSeparator5);

        jmi_volver.setBackground(new java.awt.Color(255, 102, 0));
        jmi_volver.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jmi_volver.setForeground(new java.awt.Color(255, 255, 255));
        jmi_volver.setText("Volver");
        jmi_volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jm_opciones.add(jmi_volver);

        jMenuBar1.add(jm_opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    public javax.swing.JButton jb_entrar;
    public javax.swing.JLabel jl_icono;
    public javax.swing.JLabel jl_password;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JLabel jl_usuario;
    public javax.swing.JMenu jm_opciones;
    private javax.swing.JMenuItem jmi_ayuda;
    public javax.swing.JMenuItem jmi_cambio;
    public javax.swing.JMenuItem jmi_cambio_validacion;
    public javax.swing.JMenuItem jmi_cerrar;
    public javax.swing.JMenuItem jmi_olvido;
    public javax.swing.JMenuItem jmi_volver;
    public javax.swing.JTextField jtf_password;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables

    public void getContentPane(viewLogin viewLogin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
