/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class viewUsuario extends javax.swing.JPanel {

    /**
     * Creates new form viewUsuario
     */
    public viewUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_usuarios = new javax.swing.JTable();
        jtf_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jl_datos2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jl_rfc = new javax.swing.JLabel();
        jtf_rfc = new javax.swing.JTextField();
        jl_sucursal = new javax.swing.JLabel();
        jcb_sucursal = new javax.swing.JComboBox<>();
        jl_puesto = new javax.swing.JLabel();
        jcb_puesto = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jb_modificar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jl_fondo = new javax.swing.JLabel();

        setLayout(null);

        jl_titulo.setFont(new java.awt.Font("AR DESTINE", 0, 68)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo.setText("Usuarios");
        add(jl_titulo);
        jl_titulo.setBounds(380, 20, 280, 40);

        jt_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_usuarios);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 990, 230);
        add(jtf_buscar);
        jtf_buscar.setBounds(100, 90, 480, 20);

        jLabel1.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Buscar:");
        add(jLabel1);
        jLabel1.setBounds(30, 90, 90, 20);

        jl_datos2.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_datos2.setForeground(new java.awt.Color(255, 102, 0));
        jl_datos2.setText("Datos Usuario");
        add(jl_datos2);
        jl_datos2.setBounds(20, 360, 160, 21);
        add(jSeparator3);
        jSeparator3.setBounds(20, 440, 990, 10);

        jl_rfc.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_rfc.setForeground(new java.awt.Color(255, 102, 0));
        jl_rfc.setText("RFC:");
        add(jl_rfc);
        jl_rfc.setBounds(20, 390, 40, 20);

        jtf_rfc.setEditable(false);
        jtf_rfc.setEnabled(false);
        add(jtf_rfc);
        jtf_rfc.setBounds(20, 410, 160, 20);

        jl_sucursal.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_sucursal.setForeground(new java.awt.Color(255, 102, 0));
        jl_sucursal.setText("Sucursal:");
        add(jl_sucursal);
        jl_sucursal.setBounds(210, 390, 70, 20);

        jcb_sucursal.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jcb_sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        add(jcb_sucursal);
        jcb_sucursal.setBounds(210, 410, 50, 20);

        jl_puesto.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jl_puesto.setForeground(new java.awt.Color(255, 102, 0));
        jl_puesto.setText("Puesto:");
        add(jl_puesto);
        jl_puesto.setBounds(300, 390, 70, 20);

        jcb_puesto.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jcb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDEDOR", "ADMIN" }));
        add(jcb_puesto);
        jcb_puesto.setBounds(300, 410, 100, 20);
        add(jSeparator4);
        jSeparator4.setBounds(20, 380, 990, 10);

        jb_modificar.setBackground(new java.awt.Color(255, 102, 0));
        jb_modificar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificar.setText("Modificar");
        jb_modificar.setBorder(null);
        add(jb_modificar);
        jb_modificar.setBounds(30, 460, 130, 40);

        jb_guardar.setBackground(new java.awt.Color(255, 102, 0));
        jb_guardar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");
        jb_guardar.setBorder(null);
        add(jb_guardar);
        jb_guardar.setBounds(190, 460, 130, 40);

        jb_cancelar.setBackground(new java.awt.Color(255, 102, 0));
        jb_cancelar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setBorder(null);
        add(jb_cancelar);
        jb_cancelar.setBounds(350, 460, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(960, 460, 50, 50);

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        add(jl_fondo);
        jl_fondo.setBounds(0, 0, 1060, 540);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_modificar;
    public javax.swing.JComboBox<String> jcb_puesto;
    public javax.swing.JComboBox<String> jcb_sucursal;
    private javax.swing.JLabel jl_datos2;
    private javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_puesto;
    private javax.swing.JLabel jl_rfc;
    public javax.swing.JLabel jl_sucursal;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JTable jt_usuarios;
    private javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_rfc;
    // End of variables declaration//GEN-END:variables
}
