/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class viewVendedor extends javax.swing.JPanel {

    /**
     * Creates new form viewVendedor
     */
    public viewVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pago = new javax.swing.ButtonGroup();
        js_1 = new javax.swing.JSeparator();
        jl_fecha = new javax.swing.JLabel();
        jl_titulo1 = new javax.swing.JLabel();
        jl_tipo_user = new javax.swing.JLabel();
        jl_fecha1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jb_buscar = new javax.swing.JButton();
        jb_cobrar = new javax.swing.JButton();
        jb_cancel_venta = new javax.swing.JButton();
        jb_clientes = new javax.swing.JButton();
        jb_corte = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jtf_captura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_2 = new javax.swing.JSeparator();
        jl_tipo_pago = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jrb_Efectivo = new javax.swing.JRadioButton();
        js_3 = new javax.swing.JSeparator();
        jl_tipo_pago1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jl_fondo = new javax.swing.JLabel();

        setLayout(null);
        add(js_1);
        js_1.setBounds(10, 500, 1040, 20);

        jl_fecha.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_fecha.setForeground(new java.awt.Color(255, 102, 0));
        jl_fecha.setText("08/10/2018");
        add(jl_fecha);
        jl_fecha.setBounds(940, 20, 100, 21);

        jl_titulo1.setFont(new java.awt.Font("AR DESTINE", 0, 58)); // NOI18N
        jl_titulo1.setForeground(new java.awt.Color(255, 102, 0));
        jl_titulo1.setText("Ferretería ACME");
        add(jl_titulo1);
        jl_titulo1.setBounds(250, 10, 480, 40);

        jl_tipo_user.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_tipo_user.setForeground(new java.awt.Color(255, 102, 0));
        jl_tipo_user.setText("Vendedor: NILMA01");
        add(jl_tipo_user);
        jl_tipo_user.setBounds(10, 20, 220, 20);

        jl_fecha1.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_fecha1.setForeground(new java.awt.Color(255, 102, 0));
        jl_fecha1.setText("Sucursal: 1");
        add(jl_fecha1);
        jl_fecha1.setBounds(760, 20, 100, 21);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 790, 280);

        jb_buscar.setBackground(new java.awt.Color(255, 102, 0));
        jb_buscar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jb_buscar.setText("Buscar Producto");
        jb_buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });
        add(jb_buscar);
        jb_buscar.setBounds(940, 80, 121, 60);

        jb_cobrar.setBackground(new java.awt.Color(255, 102, 0));
        jb_cobrar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_cobrar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cobrar.setText("Cobrar");
        jb_cobrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_cobrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_cobrar.setName(""); // NOI18N
        add(jb_cobrar);
        jb_cobrar.setBounds(810, 250, 120, 60);

        jb_cancel_venta.setBackground(new java.awt.Color(255, 102, 0));
        jb_cancel_venta.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_cancel_venta.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancel_venta.setText("Cancelar Venta");
        jb_cancel_venta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_cancel_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jb_cancel_venta);
        jb_cancel_venta.setBounds(940, 160, 120, 60);

        jb_clientes.setBackground(new java.awt.Color(255, 102, 0));
        jb_clientes.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_clientes.setForeground(new java.awt.Color(255, 255, 255));
        jb_clientes.setText("Clientes");
        jb_clientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jb_clientes);
        jb_clientes.setBounds(810, 80, 120, 60);

        jb_corte.setBackground(new java.awt.Color(255, 102, 0));
        jb_corte.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_corte.setForeground(new java.awt.Color(255, 255, 255));
        jb_corte.setText("Corte de caja");
        jb_corte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_corte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_corte.setName(""); // NOI18N
        add(jb_corte);
        jb_corte.setBounds(940, 250, 120, 60);

        jb_cancelar.setBackground(new java.awt.Color(255, 102, 0));
        jb_cancelar.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancelar.setText("Cancelar Producto");
        jb_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_cancelar.setName(""); // NOI18N
        add(jb_cancelar);
        jb_cancelar.setBounds(810, 160, 120, 60);

        jTextField1.setEnabled(false);
        add(jTextField1);
        jTextField1.setBounds(810, 350, 240, 20);

        jtf_captura.setBackground(new java.awt.Color(153, 153, 153));
        jtf_captura.setText("Ingresa código de Producto");
        jtf_captura.setToolTipText("");
        add(jtf_captura);
        jtf_captura.setBounds(10, 70, 790, 50);

        jLabel2.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Cliente");
        add(jLabel2);
        jLabel2.setBounds(810, 320, 100, 20);
        add(js_2);
        js_2.setBounds(10, 60, 1040, 20);

        jl_tipo_pago.setFont(new java.awt.Font("AR DESTINE", 0, 24)); // NOI18N
        jl_tipo_pago.setForeground(new java.awt.Color(255, 102, 0));
        jl_tipo_pago.setText("TOTAL");
        add(jl_tipo_pago);
        jl_tipo_pago.setBounds(10, 520, 120, 21);

        jRadioButton1.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 102, 0));
        jRadioButton1.setText("Tarjeta");
        add(jRadioButton1);
        jRadioButton1.setBounds(170, 460, 89, 29);

        jRadioButton2.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 102, 0));
        jRadioButton2.setText("Vale");
        add(jRadioButton2);
        jRadioButton2.setBounds(320, 460, 61, 29);

        jrb_Efectivo.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jrb_Efectivo.setForeground(new java.awt.Color(255, 102, 0));
        jrb_Efectivo.setText("Efectivo");
        add(jrb_Efectivo);
        jrb_Efectivo.setBounds(20, 460, 93, 29);
        add(js_3);
        js_3.setBounds(10, 440, 1040, 20);

        jl_tipo_pago1.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jl_tipo_pago1.setForeground(new java.awt.Color(255, 102, 0));
        jl_tipo_pago1.setText("Tipo de pago");
        add(jl_tipo_pago1);
        jl_tipo_pago1.setBounds(10, 410, 120, 21);

        jTextField2.setFont(new java.awt.Font("AR DESTINE", 0, 16)); // NOI18N
        jTextField2.setText("$ 0. 00");
        add(jTextField2);
        jTextField2.setBounds(110, 510, 130, 30);

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        add(jl_fondo);
        jl_fondo.setBounds(0, 0, 1100, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_pago;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JButton jb_buscar;
    public javax.swing.JButton jb_cancel_venta;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_clientes;
    public javax.swing.JButton jb_cobrar;
    public javax.swing.JButton jb_corte;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_fecha1;
    private javax.swing.JLabel jl_fondo;
    private javax.swing.JLabel jl_tipo_pago;
    private javax.swing.JLabel jl_tipo_pago1;
    private javax.swing.JLabel jl_tipo_user;
    private javax.swing.JLabel jl_titulo1;
    private javax.swing.JRadioButton jrb_Efectivo;
    private javax.swing.JSeparator js_1;
    private javax.swing.JSeparator js_2;
    private javax.swing.JSeparator js_3;
    private javax.swing.JTextField jtf_captura;
    // End of variables declaration//GEN-END:variables
}
